name: Deploy to NuGet

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  PACKAGE_OUTPUT_DIR: ${{ github.workspace }}/${{ vars.PACKAGE_OUTPUT_DIR }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build ${{ vars.PROJECT_NAME }} --no-restore --configuration Release

      - name: Get Version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Pack
        run: dotnet pack ${{ vars.PROJECT_NAME }} --no-restore --no-build --configuration Release -p:PackageVersion=${VERSION} --output ${{ env.PACKAGE_OUTPUT_DIR }}

      - name: Publish
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIR }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s ${{ vars.NUGET_SOURCE_URL }}
    
    